---
- name: process stack
  ignore_errors: True
  register: stack_create
  os_stack:
    name: "mq-{{ _apb_service_instance_id }}"
    state: "{{ state }}"
    template: "{{ role_path }}/templates/{{ service }}.template"
    environment:
    validate_certs: no
    parameters:
      queue_name: "{{ queue_name }}"
    auth:
      auth_url: "{{ url }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      project_name: "{{ project }}"
      project_domain_name: default
      user_domain_name: default
